"""Initial database schema

Revision ID: 8159ef0793f9
Revises: 
Create Date: 2025-12-16 09:33:57.409159

This migration file is auto-generated by Alembic for University LMS Backend production schema changes.

- No sample/demo changes.
- Unified for real production migrations only.
"""

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8159ef0793f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_academic_sessions_name'), 'academic_sessions', ['name'], unique=True)
    op.create_index(op.f('ix_academic_sessions_session_id'), 'academic_sessions', ['session_id'], unique=False)
    op.create_table('departments',
    sa.Column('dept_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('dept_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_dept_id'), 'departments', ['dept_id'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.create_table('rooms',
    sa.Column('room_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('building', sa.String(length=128), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_rooms_code'), 'rooms', ['code'], unique=True)
    op.create_index(op.f('ix_rooms_room_id'), 'rooms', ['room_id'], unique=False)
    op.create_table('course_catalog',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.String(length=32), nullable=False),
    sa.Column('course_name', sa.String(length=256), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_course_catalog_course_code'), 'course_catalog', ['course_code'], unique=True)
    op.create_index(op.f('ix_course_catalog_course_id'), 'course_catalog', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_catalog_dept_id'), 'course_catalog', ['dept_id'], unique=False)
    op.create_table('specializations',
    sa.Column('specialization_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('specialization_id')
    )
    op.create_index(op.f('ix_specializations_code'), 'specializations', ['code'], unique=True)
    op.create_index(op.f('ix_specializations_dept_id'), 'specializations', ['dept_id'], unique=False)
    op.create_index(op.f('ix_specializations_name'), 'specializations', ['name'], unique=True)
    op.create_index(op.f('ix_specializations_specialization_id'), 'specializations', ['specialization_id'], unique=False)
    op.create_table('course_offerings',
    sa.Column('offering_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('academic_session_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['academic_session_id'], ['academic_sessions.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['course_catalog.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.dept_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('offering_id')
    )
    op.create_index(op.f('ix_course_offerings_academic_session_id'), 'course_offerings', ['academic_session_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_course_id'), 'course_offerings', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_department_id'), 'course_offerings', ['department_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_offering_id'), 'course_offerings', ['offering_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_section'), 'course_offerings', ['section'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('profile_image_path', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('specialization_id', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.specialization_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_specialization_id'), 'users', ['specialization_id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_index(op.f('ix_admins_admin_id'), 'admins', ['admin_id'], unique=False)
    op.create_index(op.f('ix_admins_user_id'), 'admins', ['user_id'], unique=True)
    op.create_table('assignments',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('max_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.offering_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_assignments_assignment_id'), 'assignments', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignments_course_offering_id'), 'assignments', ['course_offering_id'], unique=False)
    op.create_table('associate_teachers',
    sa.Column('assoc_teacher_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.offering_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assoc_teacher_id')
    )
    op.create_index(op.f('ix_associate_teachers_assoc_teacher_id'), 'associate_teachers', ['assoc_teacher_id'], unique=False)
    op.create_index(op.f('ix_associate_teachers_course_offering_id'), 'associate_teachers', ['course_offering_id'], unique=False)
    op.create_index(op.f('ix_associate_teachers_user_id'), 'associate_teachers', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('notification_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('professors',
    sa.Column('professor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.offering_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.dept_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('professor_id')
    )
    op.create_index(op.f('ix_professors_course_offering_id'), 'professors', ['course_offering_id'], unique=False)
    op.create_index(op.f('ix_professors_department_id'), 'professors', ['department_id'], unique=False)
    op.create_index(op.f('ix_professors_professor_id'), 'professors', ['professor_id'], unique=False)
    op.create_index(op.f('ix_professors_user_id'), 'professors', ['user_id'], unique=False)
    op.create_table('section_groups',
    sa.Column('section_group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.offering_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_group_id')
    )
    op.create_index(op.f('ix_section_groups_course_offering_id'), 'section_groups', ['course_offering_id'], unique=False)
    op.create_index(op.f('ix_section_groups_name'), 'section_groups', ['name'], unique=False)
    op.create_index(op.f('ix_section_groups_section_group_id'), 'section_groups', ['section_group_id'], unique=False)
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.specialization_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_index(op.f('ix_students_specialization_id'), 'students', ['specialization_id'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=False)
    op.create_index(op.f('ix_students_user_id'), 'students', ['user_id'], unique=True)
    op.create_table('uploaded_files',
    sa.Column('file_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_uploaded_files_file_id'), 'uploaded_files', ['file_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_user_id'), 'uploaded_files', ['user_id'], unique=False)
    op.create_table('assignment_files',
    sa.Column('file_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_assignment_files_assignment_id'), 'assignment_files', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_files_file_id'), 'assignment_files', ['file_id'], unique=False)
    op.create_table('assignment_submissions',
    sa.Column('submission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('digital_content', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('graded_by_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.String(length=16), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['graded_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_index(op.f('ix_assignment_submissions_assignment_id'), 'assignment_submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assignment_submissions_student_id'), 'assignment_submissions', ['student_id'], unique=False)
    op.create_index(op.f('ix_assignment_submissions_submission_id'), 'assignment_submissions', ['submission_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('section_group_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.offering_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_group_id'], ['section_groups.section_group_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    op.create_index(op.f('ix_enrollments_course_offering_id'), 'enrollments', ['course_offering_id'], unique=False)
    op.create_index(op.f('ix_enrollments_enrollment_id'), 'enrollments', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_enrollments_section_group_id'), 'enrollments', ['section_group_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('quiz_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.offering_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quiz_id')
    )
    op.create_index(op.f('ix_quizzes_assignment_id'), 'quizzes', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_quizzes_course_offering_id'), 'quizzes', ['course_offering_id'], unique=False)
    op.create_index(op.f('ix_quizzes_quiz_id'), 'quizzes', ['quiz_id'], unique=False)
    op.create_table('scheduled_slots',
    sa.Column('slot_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.String(length=16), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.offering_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.professor_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_index(op.f('ix_scheduled_slots_course_offering_id'), 'scheduled_slots', ['course_offering_id'], unique=False)
    op.create_index(op.f('ix_scheduled_slots_professor_id'), 'scheduled_slots', ['professor_id'], unique=False)
    op.create_index(op.f('ix_scheduled_slots_room_id'), 'scheduled_slots', ['room_id'], unique=False)
    op.create_index(op.f('ix_scheduled_slots_slot_id'), 'scheduled_slots', ['slot_id'], unique=False)
    op.create_table('student_section_assignments',
    sa.Column('assignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('section_group_id', sa.Integer(), nullable=False),
    sa.Column('course_offering_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.offering_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_group_id'], ['section_groups.section_group_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_index(op.f('ix_student_section_assignments_assignment_id'), 'student_section_assignments', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_student_section_assignments_course_offering_id'), 'student_section_assignments', ['course_offering_id'], unique=False)
    op.create_index(op.f('ix_student_section_assignments_section_group_id'), 'student_section_assignments', ['section_group_id'], unique=False)
    op.create_index(op.f('ix_student_section_assignments_student_id'), 'student_section_assignments', ['student_id'], unique=False)
    op.create_table('grades',
    sa.Column('grade_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('course_offering_id', sa.Integer(), nullable=True),
    sa.Column('grade_value', sa.String(length=16), nullable=False),
    sa.Column('numeric_score', sa.Float(), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.offering_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.quiz_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grade_id')
    )
    op.create_index(op.f('ix_grades_assignment_id'), 'grades', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_grades_course_offering_id'), 'grades', ['course_offering_id'], unique=False)
    op.create_index(op.f('ix_grades_grade_id'), 'grades', ['grade_id'], unique=False)
    op.create_index(op.f('ix_grades_quiz_id'), 'grades', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.quiz_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index(op.f('ix_questions_assignment_id'), 'questions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_questions_question_id'), 'questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_questions_quiz_id'), 'questions', ['quiz_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('attempt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('is_graded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.quiz_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_quiz_attempts_attempt_id'), 'quiz_attempts', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_student_id'), 'quiz_attempts', ['student_id'], unique=False)
    op.create_table('quiz_files',
    sa.Column('file_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.quiz_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index(op.f('ix_quiz_files_file_id'), 'quiz_files', ['file_id'], unique=False)
    op.create_index(op.f('ix_quiz_files_quiz_id'), 'quiz_files', ['quiz_id'], unique=False)
    op.create_table('question_options',
    sa.Column('option_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_index(op.f('ix_question_options_option_id'), 'question_options', ['option_id'], unique=False)
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    op.create_table('quiz_file_submissions',
    sa.Column('file_submission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.attempt_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_submission_id')
    )
    op.create_index(op.f('ix_quiz_file_submissions_attempt_id'), 'quiz_file_submissions', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_quiz_file_submissions_file_submission_id'), 'quiz_file_submissions', ['file_submission_id'], unique=False)
    op.create_index(op.f('ix_quiz_file_submissions_question_id'), 'quiz_file_submissions', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_file_submissions_student_id'), 'quiz_file_submissions', ['student_id'], unique=False)
    op.create_table('quiz_answers',
    sa.Column('answer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score_awarded', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.attempt_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.option_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_index(op.f('ix_quiz_answers_answer_id'), 'quiz_answers', ['answer_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_attempt_id'), 'quiz_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_question_id'), 'quiz_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_answers_student_id'), 'quiz_answers', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_answers_student_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_question_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_attempt_id'), table_name='quiz_answers')
    op.drop_index(op.f('ix_quiz_answers_answer_id'), table_name='quiz_answers')
    op.drop_table('quiz_answers')
    op.drop_index(op.f('ix_quiz_file_submissions_student_id'), table_name='quiz_file_submissions')
    op.drop_index(op.f('ix_quiz_file_submissions_question_id'), table_name='quiz_file_submissions')
    op.drop_index(op.f('ix_quiz_file_submissions_file_submission_id'), table_name='quiz_file_submissions')
    op.drop_index(op.f('ix_quiz_file_submissions_attempt_id'), table_name='quiz_file_submissions')
    op.drop_table('quiz_file_submissions')
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_index(op.f('ix_question_options_option_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index(op.f('ix_quiz_files_quiz_id'), table_name='quiz_files')
    op.drop_index(op.f('ix_quiz_files_file_id'), table_name='quiz_files')
    op.drop_table('quiz_files')
    op.drop_index(op.f('ix_quiz_attempts_student_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_attempt_id'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_questions_quiz_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_question_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_assignment_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_grades_student_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_quiz_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_grade_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_course_offering_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_assignment_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_student_section_assignments_student_id'), table_name='student_section_assignments')
    op.drop_index(op.f('ix_student_section_assignments_section_group_id'), table_name='student_section_assignments')
    op.drop_index(op.f('ix_student_section_assignments_course_offering_id'), table_name='student_section_assignments')
    op.drop_index(op.f('ix_student_section_assignments_assignment_id'), table_name='student_section_assignments')
    op.drop_table('student_section_assignments')
    op.drop_index(op.f('ix_scheduled_slots_slot_id'), table_name='scheduled_slots')
    op.drop_index(op.f('ix_scheduled_slots_room_id'), table_name='scheduled_slots')
    op.drop_index(op.f('ix_scheduled_slots_professor_id'), table_name='scheduled_slots')
    op.drop_index(op.f('ix_scheduled_slots_course_offering_id'), table_name='scheduled_slots')
    op.drop_table('scheduled_slots')
    op.drop_index(op.f('ix_quizzes_quiz_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_course_offering_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_assignment_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_section_group_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_enrollment_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_offering_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_assignment_submissions_submission_id'), table_name='assignment_submissions')
    op.drop_index(op.f('ix_assignment_submissions_student_id'), table_name='assignment_submissions')
    op.drop_index(op.f('ix_assignment_submissions_assignment_id'), table_name='assignment_submissions')
    op.drop_table('assignment_submissions')
    op.drop_index(op.f('ix_assignment_files_file_id'), table_name='assignment_files')
    op.drop_index(op.f('ix_assignment_files_assignment_id'), table_name='assignment_files')
    op.drop_table('assignment_files')
    op.drop_index(op.f('ix_uploaded_files_user_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_file_id'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_students_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_specialization_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_section_groups_section_group_id'), table_name='section_groups')
    op.drop_index(op.f('ix_section_groups_name'), table_name='section_groups')
    op.drop_index(op.f('ix_section_groups_course_offering_id'), table_name='section_groups')
    op.drop_table('section_groups')
    op.drop_index(op.f('ix_professors_user_id'), table_name='professors')
    op.drop_index(op.f('ix_professors_professor_id'), table_name='professors')
    op.drop_index(op.f('ix_professors_department_id'), table_name='professors')
    op.drop_index(op.f('ix_professors_course_offering_id'), table_name='professors')
    op.drop_table('professors')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_associate_teachers_user_id'), table_name='associate_teachers')
    op.drop_index(op.f('ix_associate_teachers_course_offering_id'), table_name='associate_teachers')
    op.drop_index(op.f('ix_associate_teachers_assoc_teacher_id'), table_name='associate_teachers')
    op.drop_table('associate_teachers')
    op.drop_index(op.f('ix_assignments_course_offering_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_assignment_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_admins_user_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_admin_id'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_specialization_id'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_course_offerings_section'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_offering_id'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_department_id'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_course_id'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_academic_session_id'), table_name='course_offerings')
    op.drop_table('course_offerings')
    op.drop_index(op.f('ix_specializations_specialization_id'), table_name='specializations')
    op.drop_index(op.f('ix_specializations_name'), table_name='specializations')
    op.drop_index(op.f('ix_specializations_dept_id'), table_name='specializations')
    op.drop_index(op.f('ix_specializations_code'), table_name='specializations')
    op.drop_table('specializations')
    op.drop_index(op.f('ix_course_catalog_dept_id'), table_name='course_catalog')
    op.drop_index(op.f('ix_course_catalog_course_id'), table_name='course_catalog')
    op.drop_index(op.f('ix_course_catalog_course_code'), table_name='course_catalog')
    op.drop_table('course_catalog')
    op.drop_index(op.f('ix_rooms_room_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_code'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_departments_dept_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_academic_sessions_session_id'), table_name='academic_sessions')
    op.drop_index(op.f('ix_academic_sessions_name'), table_name='academic_sessions')
    op.drop_table('academic_sessions')
    # ### end Alembic commands ###