#!/usr/bin/env python3
"""
Quick Start Example: Using Database Seeding
-------------------------------------------
This example demonstrates how to use the database seeding functionality
in the University LMS backend.

Usage scenarios:
1. Automatic seeding on startup
2. Manual seeding via script
3. Programmatic seeding
"""

import os
import sys
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, str(Path(__file__).parent.parent))

def example_1_automatic_seeding():
    """
    Example 1: Automatic seeding on application startup
    
    When SEED_ON_STARTUP is set to 'true', the application will automatically
    run the seeding script when it starts.
    """
    print("=" * 70)
    print("EXAMPLE 1: Automatic Seeding on Startup")
    print("=" * 70)
    print()
    print("1. Set environment variable:")
    print("   export SEED_ON_STARTUP=true")
    print()
    print("2. Start the application:")
    print("   python -m app.main")
    print("   # or")
    print("   uvicorn app.main:app --reload")
    print()
    print("3. The seeding script will run automatically before the app starts")
    print("   and create 1000+ records with realistic data.")
    print()


def example_2_manual_seeding():
    """
    Example 2: Manual seeding via command line
    
    Run the seeding script directly from the command line.
    """
    print("=" * 70)
    print("EXAMPLE 2: Manual Seeding")
    print("=" * 70)
    print()
    print("Run the seeding script directly:")
    print("   python scripts/seed_database.py")
    print()
    print("This will:")
    print("   • Connect to your configured database")
    print("   • Create roles, departments, and specializations")
    print("   • Generate 1000+ users (professors, associates, students)")
    print("   • Create course offerings and enrollments")
    print("   • Generate assignments, grades, and quizzes")
    print()


def example_3_programmatic_seeding():
    """
    Example 3: Programmatic seeding
    
    Import and use seeding functions in your own code.
    """
    print("=" * 70)
    print("EXAMPLE 3: Programmatic Seeding")
    print("=" * 70)
    print()
    print("You can import and use the seeding script programmatically:")
    print()
    print("```python")
    print("import sys")
    print("from pathlib import Path")
    print()
    print("# Import the seeding module")
    print("sys.path.insert(0, str(Path(__file__).parent.parent))")
    print("from scripts import seed_database")
    print()
    print("# Run the main seeding function")
    print("seed_database.main()")
    print("```")
    print()


def print_sample_credentials():
    """Print sample credentials for accessing the system."""
    print("=" * 70)
    print("SAMPLE CREDENTIALS AFTER SEEDING")
    print("=" * 70)
    print()
    print("🔐 Admin Access:")
    print("   Username: admin_user")
    print("   Password: Admin@12345!")
    print()
    print("👨‍🏫 Professor Access (example):")
    print("   Username: prof_smith_0")
    print("   Password: prof_smith_0@Pass123!")
    print()
    print("👨‍🎓 Student Access (example):")
    print("   Username: student_jones_0")
    print("   Password: student_jones_0@Pass123!")
    print()
    print("📝 Note: Actual usernames depend on Faker-generated names.")
    print("    Password pattern: [username]@Pass123!")
    print()


def print_data_summary():
    """Print summary of what data gets created."""
    print("=" * 70)
    print("DATA GENERATED BY SEEDING SCRIPT")
    print("=" * 70)
    print()
    print("📊 Users & Roles:")
    print("   • 1 Administrator")
    print("   • 50 Professors")
    print("   • 80 Associate Teachers (TAs)")
    print("   • 900 Students")
    print()
    print("🏛️  Academic Structure:")
    print("   • 15 Departments")
    print("   • 20 Specializations")
    print("   • 8 Academic Sessions")
    print()
    print("📚 Courses:")
    print("   • 100 Courses in catalog")
    print("   • 200+ Course offerings")
    print("   • 2,700+ Student enrollments")
    print()
    print("📝 Assessments:")
    print("   • 600+ Assignments")
    print("   • 15,000+ Grades")
    print("   • 100+ Quizzes")
    print()


def print_configuration():
    """Print configuration information."""
    print("=" * 70)
    print("CONFIGURATION")
    print("=" * 70)
    print()
    print("Required environment variables:")
    print("   DATABASE_URL - PostgreSQL connection string")
    print("   SEED_ON_STARTUP - Set to 'true' for automatic seeding")
    print()
    print("Example .env configuration:")
    print()
    print("   DATABASE_URL=postgresql+psycopg2://user:pass@localhost:5432/lms")
    print("   SEED_ON_STARTUP=true")
    print()


def main():
    """Run all examples."""
    print()
    print("╔" + "═" * 68 + "╗")
    print("║" + " " * 15 + "UNIVERSITY LMS DATABASE SEEDING" + " " * 22 + "║")
    print("║" + " " * 20 + "Quick Start Examples" + " " * 28 + "║")
    print("╚" + "═" * 68 + "╝")
    print()
    
    example_1_automatic_seeding()
    example_2_manual_seeding()
    example_3_programmatic_seeding()
    print_configuration()
    print_data_summary()
    print_sample_credentials()
    
    print("=" * 70)
    print("For detailed documentation, see:")
    print("   scripts/README_SEEDING.md")
    print("=" * 70)
    print()


if __name__ == "__main__":
    main()
