/**
 * Textarea Component
 * ----------------------------------------------------------------------------
 * Global, production-grade textarea for LMS UI.
 * - All style and layout are governed by textarea.module.scss (design system).
 * - ARIA and accessible for all fields (label, error/help ARIA, etc).
 * - Both controlled and uncontrolled usage supported.
 * - No sample/demo logic present.
 *
 * Props:
 * - id?: string                         // For accessibility and label (autogenerated if omitted)
 * - label?: string | ReactNode          // Optional field label above textarea
 * - error?: string | ReactNode          // Optional error text below
 * - help?: string | ReactNode           // Optional help/hint text below
 * - className?: string                  // Extra classes for wrapper
 * - textareaClassName?: string          // Extra classes for textarea field
 * - ...rest: All native <textarea> props (value, onChange, rows, etc)
 */

import PropTypes from 'prop-types';
import { useId } from 'react';
import styles from './textarea.module.scss';

export default function Textarea({
  id,
  label,
  error,
  help,
  className = '',
  textareaClassName = '',
  ...rest
}) {
  // For a11y: label/input association
  const generatedId = useId();
  const textareaId = id || generatedId;

  // Design system classes
  const wrapperClass = [styles.textarea__wrapper, className].filter(Boolean).join(' ');
  const fieldClass = [
    styles.textarea,
    error ? styles['textarea--error'] : '',
    textareaClassName,
  ].filter(Boolean).join(' ');

  // aria-describedby
  const describedByIds = [];
  if (help) describedByIds.push(`${textareaId}-help`);
  if (error) describedByIds.push(`${textareaId}-error`);
  const ariaDescribedBy = describedByIds.length ? describedByIds.join(' ') : undefined;

  return (
    <div className={wrapperClass}>
      {label && (
        <label htmlFor={textareaId} className={styles.textarea__label}>
          {label}
        </label>
      )}
      <textarea
        id={textareaId}
        className={fieldClass}
        aria-invalid={!!error}
        aria-describedby={ariaDescribedBy}
        {...rest}
      />
      {help && (
        <div id={`${textareaId}-help`} className={styles.textarea__help}>
          {help}
        </div>
      )}
      {error && (
        <div id={`${textareaId}-error`} className={styles.textarea__error}>
          {error}
        </div>
      )}
    </div>
  );
}

Textarea.propTypes = {
  id: PropTypes.string,
  label: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
  error: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
  help: PropTypes.oneOfType([PropTypes.string, PropTypes.node]),
  className: PropTypes.string,
  textareaClassName: PropTypes.string,
};

/**
 * Production/Architecture Notes:
 * - All theming, border, error, and spacing come from textarea.module.scss.
 * - Strict design-system and ARIA/label/describe handling.
 * - No local/sample logic—ready for all forms and content areas.
 */